# Code generated by TkForge <https://github.com/axorax/tkforge>
# Donate to support TkForge! <https://www.patreon.com/axorax>

import os
import sys
import tkinter as tk

def load_asset(path):
    base = getattr(sys, '_MEIPASS', os.path.dirname(os.path.abspath(__file__)))
    assets = os.path.join(base, "assets")
    return os.path.join(assets, path)

window = tk.Tk()
window.geometry("500x350")
window.configure(bg="#ffffff")
window.title("AssetManager")

canvas = tk.Canvas(
    window,
    bg = "#ffffff",
    width = 500,
    height = 350,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x=0, y=0)

canvas.create_rectangle(0, 0, 500, 350, fill='#303030', outline="")

canvas.create_text(
    164,
    18,
    anchor="nw",
    text="AssetManager",
    fill="#f5f5f5",
    font=("Istok Web", 24 * -1)
)

edit_button_img = tk.PhotoImage(file=load_asset("edit_button.png"))

button_1 = tk.Button(
    image=edit_button_img,
    relief="flat",
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 has been pressed!")
)

button_1.place(x=158, y=312, width=185, height=38)

canvas.create_text(
    158,
    312,
    anchor="nw",
    text="",
    fill="#000000",
    font=("Default Font", 12 * -1)
)

back_button_img = tk.PhotoImage(file=load_asset("back_button.png"))

button_2 = tk.Button(
    image=back_button_img,
    relief="flat",
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 has been pressed!")
)

button_2.place(x=1, y=0, width=99, height=29)

canvas.create_text(
    1,
    0,
    anchor="nw",
    text="",
    fill="#000000",
    font=("Default Font", 12 * -1)
)

listbox_1 = tk.Listbox(width=32, height=16)

# Creating a Scrollbar and  
# attaching it to root window 
scrollbar_1 = tk.Scrollbar(window)
scrollbar_1.place(x=345, y=55, height=260)

listbox_1.config(yscrollcommand = scrollbar_1.set)

scrollbar_1.config(command = listbox_1.yview) 

for i in range(100):
    listbox_1.insert(tk.END, f"Item {i}")

listbox_1.place(x=150, y=55)

window.resizable(False, False)
window.mainloop()
