# Code generated by TkForge <https://github.com/axorax/tkforge>
# Donate to support TkForge! <https://www.patreon.com/axorax>

import os
import sys
import tkinter as tk

class TkForge_Entry(tk.Entry):
    def __init__(self, master=None, placeholder="Enter text", placeholder_fg='grey', **kwargs):
        super().__init__(master, **kwargs)
        
        self.p, self.p_fg, self.fg = placeholder, placeholder_fg, self.cget("fg")
        self.putp()
        self.bind("<FocusIn>", self.toggle)
        self.bind("<FocusOut>", self.toggle)

    def putp(self):
        self.delete(0, tk.END)
        self.insert(0, self.p)
        self.config(fg=self.p_fg)
        self.p_a = True

    def toggle(self, event):
        if self.p_a:
            self.delete(0, tk.END)
            self.config(fg=self.fg)
            self.p_a = False
        elif not self.get(): self.putp()

    def get(self): return '' if self.p_a else super().get()

    def is_placeholder(self, b):
        self.p_a = b
        self.config(fg=self.p_fg if b == True else self.fg)

    def get_placeholder(self): return self.p

class TkForge_Textarea(tk.Text):
    def __init__(self, master=None, placeholder="Enter text", placeholder_fg='grey', **kwargs):
        super().__init__(master, **kwargs)
        
        self.p, self.p_fg, self.fg = placeholder, placeholder_fg, self.cget("fg")
        self.putp()
        self.bind("<FocusIn>", self.toggle)
        self.bind("<FocusOut>", self.toggle)

    def putp(self):
        self.delete('1.0', tk.END)
        self.insert('1.0', self.p)
        self.config(fg=self.p_fg)
        self.p_a = True

    def toggle(self, event):
        if self.p_a:
            self.delete('1.0', tk.END)
            self.config(fg=self.fg)
            self.p_a = False
        elif self.get('1.0', tk.END).replace(' ', '').replace('\n', '') == '': self.putp()

    def get(self, i1='1.0', i2=tk.END): return '' if self.p_a else super().get(i1, i2)

    def is_placeholder(self, b):
        self.p_a = b
        self.config(fg=self.p_fg if b == True else self.fg)

    def get_placeholder(self): return self.p

def load_asset(path):
    base = getattr(sys, '_MEIPASS', os.path.dirname(os.path.abspath(__file__)))
    assets = os.path.join(base, "assets")
    return os.path.join(assets, path)

window = tk.Tk()
window.geometry("500x350")
window.configure(bg="#ffffff")
window.title("AssetManager")

canvas = tk.Canvas(
    window,
    bg = "#ffffff",
    width = 500,
    height = 350,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x=0, y=0)

canvas.create_rectangle(0, 0, 500, 350, fill='#303030', outline="")

canvas.create_text(
    164,
    18,
    anchor="nw",
    text="AssetManager",
    fill="#f5f5f5",
    font=("Istok Web", 24 * -1)
)

edit_button_img = tk.PhotoImage(file=load_asset("edit_button.png"))

button_1 = tk.Button(
    image=edit_button_img,
    relief="flat",
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 has been pressed!")
)

button_1.place(x=158, y=312, width=185, height=38)

canvas.create_text(
    158,
    312,
    anchor="nw",
    text="",
    fill="#000000",
    font=("Default Font", 12 * -1)
)

back_button_img = tk.PhotoImage(file=load_asset("back_button.png"))

button_2 = tk.Button(
    image=back_button_img,
    relief="flat",
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 has been pressed!")
)

button_2.place(x=1, y=0, width=99, height=29)

canvas.create_text(
    1,
    0,
    anchor="nw",
    text="",
    fill="#000000",
    font=("Default Font", 12 * -1)
)

textbox_1 = TkForge_Entry(
    bd=0,
    bg="#d9d9d9",
    fg="#ffffff",
    placeholder="#FIXME",
    insertbackground="#ffffff",
    highlightthickness=0
)

textbox_1.place(x=256, y=77, width=180, height=25)

textbox_2 = TkForge_Entry(
    bd=0,
    bg="#d9d9d9",
    fg="#ffffff",
    placeholder="#FIXME",
    insertbackground="#ffffff",
    highlightthickness=0
)

textbox_2.place(x=66, y=77, width=180, height=25)

textarea_1 = TkForge_Textarea(
    bd=0,
    bg="#d9d9d9",
    fg="#ffffff",
    placeholder="#FIXME",
    insertbackground="#ffffff",
    highlightthickness=0
)

textarea_1.place(x=256, y=173, width=180, height=127)

textbox_3 = TkForge_Entry(
    bd=0,
    bg="#d9d9d9",
    fg="#ffffff",
    placeholder="#FIXME",
    insertbackground="#ffffff",
    highlightthickness=0
)

textbox_3.place(x=66, y=125, width=180, height=25)

textbox_4 = TkForge_Entry(
    bd=0,
    bg="#d9d9d9",
    fg="#ffffff",
    placeholder="#FIXME",
    insertbackground="#ffffff",
    highlightthickness=0
)

textbox_4.place(x=256, y=125, width=180, height=25)

textbox_5 = TkForge_Entry(
    bd=0,
    bg="#d9d9d9",
    fg="#ffffff",
    placeholder="#FIXME",
    insertbackground="#ffffff",
    highlightthickness=0
)

textbox_5.place(x=66, y=173, width=180, height=25)

textbox_6 = TkForge_Entry(
    bd=0,
    bg="#d9d9d9",
    fg="#ffffff",
    placeholder="#FIXME",
    insertbackground="#ffffff",
    highlightthickness=0
)

textbox_6.place(x=67, y=274, width=180, height=25)

textbox_7 = TkForge_Entry(
    bd=0,
    bg="#d9d9d9",
    fg="#ffffff",
    placeholder="#FIXME",
    insertbackground="#ffffff",
    highlightthickness=0
)

textbox_7.place(x=67, y=223, width=180, height=25)

canvas.create_text(
    116,
    102,
    anchor="nw",
    text="Service Tag",
    fill="#ffffff",
    font=("Istok Web", 14 * -1)
)

canvas.create_text(
    288,
    102,
    anchor="nw",
    text="End Of Warranty",
    fill="#ffffff",
    font=("Istok Web", 14 * -1)
)

canvas.create_text(
    107,
    150,
    anchor="nw",
    text="Purchase Date",
    fill="#ffffff",
    font=("Istok Web", 14 * -1)
)

canvas.create_text(
    326,
    150,
    anchor="nw",
    text="Notes",
    fill="#ffffff",
    font=("Istok Web", 14 * -1)
)

canvas.create_text(
    104,
    248,
    anchor="nw",
    text="Location/Office",
    fill="#ffffff",
    font=("Istok Web", 14 * -1)
)

canvas.create_text(
    111,
    196,
    anchor="nw",
    text="Model Name",
    fill="#ffffff",
    font=("Istok Web", 14 * -1)
)

canvas.create_text(
    116,
    51,
    anchor="nw",
    text="Asset Name",
    fill="#ffffff",
    font=("Istok Web", 14 * -1)
)

canvas.create_text(
    291,
    51,
    anchor="nw",
    text="Asset Owner",
    fill="#ffffff",
    font=("Istok Web", 14 * -1)
)

window.resizable(False, False)
window.mainloop()
