# Code generated by TkForge <https://github.com/axorax/tkforge>
# Donate to support TkForge! <https://www.patreon.com/axorax>

import os
import sys
import tkinter as tk

def load_asset(path):
    base = getattr(sys, '_MEIPASS', os.path.dirname(os.path.abspath(__file__)))
    assets = os.path.join(base, "assets")
    return os.path.join(assets, path)

window = tk.Tk()
window.geometry("500x350")
window.configure(bg="#ffffff")
window.title("Untitled")

canvas = tk.Canvas(
    window,
    bg = "#ffffff",
    width = 500,
    height = 350,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x=0, y=0)

canvas.create_rectangle(0, 0, 500, 350, fill='#303030', outline="")

canvas.create_text(
    164,
    18,
    anchor="nw",
    text="AssetManager",
    fill="#f5f5f5",
    font=("Istok Web", 24 * -1)
)

button_1_image = tk.PhotoImage(file=load_asset("1.png"))

button_1 = tk.Button(
    image=button_1_image,
    relief="flat",
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 has been pressed!")
)

button_1.place(x=158, y=311, width=185, height=38)

canvas.create_text(
    157,
    309,
    anchor="nw",
    text="",
    fill="#000000",
    font=("Default Font", 12 * -1)
)

button_2_image = tk.PhotoImage(file=load_asset("2.png"))

button_2 = tk.Button(
    image=button_2_image,
    relief="flat",
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 has been pressed!")
)

button_2.place(x=1, y=0, width=99, height=29)

canvas.create_text(
    1,
    0,
    anchor="nw",
    text="",
    fill="#000000",
    font=("Default Font", 12 * -1)
)

textbox_1 = tk.Entry(
    bd=0,
    bg="#d9d9d9",
    fg="#ffffff",
    insertbackground="#ffffff",
    highlightthickness=0
)

textbox_1.place(x=256, y=77, width=180, height=25)

textbox_2 = tk.Entry(
    bd=0,
    bg="#d9d9d9",
    fg="#ffffff",
    insertbackground="#ffffff",
    highlightthickness=0
)

textbox_2.place(x=66, y=77, width=180, height=25)

textarea_1 = tk.Text(
    bd=0,
    bg="#d9d9d9",
    fg="#ffffff",
    insertbackground="#ffffff",
    highlightthickness=0
)

textarea_1.place(x=256, y=173, width=180, height=127)

textbox_3 = tk.Entry(
    bd=0,
    bg="#d9d9d9",
    fg="#ffffff",
    insertbackground="#ffffff",
    highlightthickness=0
)

textbox_3.place(x=66, y=125, width=180, height=25)

textbox_4 = tk.Entry(
    bd=0,
    bg="#d9d9d9",
    fg="#ffffff",
    insertbackground="#ffffff",
    highlightthickness=0
)

textbox_4.place(x=256, y=125, width=180, height=25)

textbox_5 = tk.Entry(
    bd=0,
    bg="#d9d9d9",
    fg="#ffffff",
    insertbackground="#ffffff",
    highlightthickness=0
)

textbox_5.place(x=66, y=173, width=180, height=25)

textbox_6 = tk.Entry(
    bd=0,
    bg="#d9d9d9",
    fg="#ffffff",
    insertbackground="#ffffff",
    highlightthickness=0
)

textbox_6.place(x=67, y=274, width=180, height=25)

textbox_7 = tk.Entry(
    bd=0,
    bg="#d9d9d9",
    fg="#ffffff",
    insertbackground="#ffffff",
    highlightthickness=0
)

textbox_7.place(x=67, y=223, width=180, height=25)

canvas.create_text(
    116,
    102,
    anchor="nw",
    text="Service Tag",
    fill="#ffffff",
    font=("Istok Web", 14 * -1)
)

canvas.create_text(
    288,
    102,
    anchor="nw",
    text="End Of Warranty",
    fill="#ffffff",
    font=("Istok Web", 14 * -1)
)

canvas.create_text(
    107,
    150,
    anchor="nw",
    text="Purchase Date",
    fill="#ffffff",
    font=("Istok Web", 14 * -1)
)

canvas.create_text(
    326,
    150,
    anchor="nw",
    text="Notes",
    fill="#ffffff",
    font=("Istok Web", 14 * -1)
)

canvas.create_text(
    104,
    248,
    anchor="nw",
    text="Location/Office",
    fill="#ffffff",
    font=("Istok Web", 14 * -1)
)

canvas.create_text(
    111,
    196,
    anchor="nw",
    text="Model Name",
    fill="#ffffff",
    font=("Istok Web", 14 * -1)
)

canvas.create_text(
    116,
    51,
    anchor="nw",
    text="Asset Name",
    fill="#ffffff",
    font=("Istok Web", 14 * -1)
)

canvas.create_text(
    291,
    51,
    anchor="nw",
    text="Asset Owner",
    fill="#ffffff",
    font=("Istok Web", 14 * -1)
)

window.resizable(False, False)
window.mainloop()
